examples/app_template/base_app/models.py
"""
Data Models Module
------------------

Create the datamodels for the app and add them to the database using sqlalchemy

"""

from sqlalchemy import Column, String, Float, DateTime, Table, BigInteger, \
    ForeignKey, Integer, Date, Boolean, UniqueConstraint, \
    func, collate, Index, and_, event
from sqlalchemy.ext.compiler import compiles
from sqlalchemy.orm import backref, aliased
from sqlalchemy.ext.associationproxy import association_proxy
from sqlalchemy.types import VARCHAR
from sqlalchemy.sql.expression import FunctionElement
from sqlalchemy.ext.hybrid import hybrid_property, hybrid_method
from flask_security import UserMixin, RoleMixin
from flask.ext.reporting.models import ReportsMixin, AnalysisMixin, \
    SavedTablesMixin

from .extensions import db, frontend


class BaseModel():
    id = Column(Integer, primary_key=True, autoincrement=True)


class CaseInsensitive(FunctionElement):
    """Case insensitive element that can be used as a SQL index

    Note that this can only be compiled on postgresql and sqlite databases.

    """

    __visit_name__ = 'notacolumn'
    name = 'CaseInsensitive'
    type = VARCHAR()


@compiles(CaseInsensitive, 'sqlite')
def case_insensitive_sqlite(element, compiler, **kw):
    arg1, = list(element.clauses)
    return compiler.process(collate(arg1, 'nocase'), **kw)


@compiles(CaseInsensitive, 'postgresql')
def case_insensitive_postgresql(element, compiler, **kw):
    arg1, = list(element.clauses)
    return compiler.process(func.lower(arg1), **kw)

examples/app_template/base_app/security_manager/forms.py
from flask.ext.security import RegisterForm, ConfirmRegisterForm
from wtforms import TextField
from wtforms.validators import Required, Optional
from wtforms.form import Form
import flask.ext.wtf as flask_wtf

class OrderedFields(Form):

    def __iter__(self):
        field_order = getattr(self, 'field_order', None)
        if field_order:
            temp_fields = []
            for name in field_order:
                if name == '*':
                    temp_fields.extend([f for f in self._unbound_fields if f[0] not in field_order])
                else:
                    temp_fields.append([f for f in self._unbound_fields if f[0] == name][0])
            self._unbound_fields = temp_fields
        return super(OrderedFields, self).__iter__()


class NameRegisterForm(OrderedFields, RegisterForm):
    name = TextField('Name', [Required()])
    field_order = ('name', '*')


class ChangeUserDetailsForm(flask_wtf.Form):
    name = TextField('Name', [Optional()])
    email = TextField('Email Address', [Optional()])

examples/app_template/base_app/app.py
"""
.. module:: app
    :synopsis: Initialisation of the Flask app

.. moduleauthor:: Sentilus Associates

"""

import os
from os import path
import logging
from logging.handlers import SMTPHandler

from flask import Flask
from flask.ext.security import SQLAlchemyUserDatastore
from .security_manager.views import security_manager
from .security_manager.security_models import User, Role, user_role
from .security_manager.forms import NameRegisterForm
from .home.views import home
from .extensions import *


__all__ = ['create_app']


def create_app(config=None, app_name=None):
    """Create the Flask app

    :type config: BaseConfig
    :param config:
        Configuration class for the app
    :type app_name: str
    :param app_name:
        Application name - important for registering blueprints

    :returns: An application object
    :rtype : flask.Flask

    """
    # Reverts to package name if None
    if app_name is None:
        app_name = 'base_app'

    app = Flask(app_name, template_folder='templates')
    app.config.from_object(config)

    return app


def setup_app(app):
    with app.app_context():
        configure_logging(app)
        app.register_blueprint(security_manager)
        app.register_blueprint(home)
        configure_extensions(app)

    return app


def configure_extensions(app):

    """Initiate the specified extensions on the app. """

    db.init_app(app)
    app.logger.info('Database initialised')

    admin.init_app(app)
    app.logger.info('Admin initialised')

    frontend.init_app(app, db, user=User, role=Role, user_role=user_role)
    app.logger.info('Sentilus frontend initialised')

    app.config['user_datastore'] = SQLAlchemyUserDatastore(db, User, Role)
    security.init_app(app, app.config['user_datastore'],
                      register_form=NameRegisterForm, confirm_register_form=NameRegisterForm)
    app.logger.info('Security initialised')

    mail.init_app(app)
    app.logger.info('Mail initialised')

    celery_app.config_from_object(app)
    app.logger.info('Celery initialised')


def configure_logging(app, logging_level=logging.INFO):
    """Configure file(info) and email(error) logging.

    If app.debug or app.testing:
        Skip debug and test mode - Just check standard output.

    Suppresses DEBUG messages by default.

    """
    app.logger.setLevel(logging_level)

    info_log = os.path.join(app.config['LOG_FOLDER'], 'info.log')
    info_file_handler = logging.FileHandler(info_log)
    info_file_handler.setLevel(logging.INFO)
    info_file_handler.setFormatter(logging.Formatter(
        '%(asctime)s %(levelname)s: %(message)s '
        '[in %(pathname)s:%(lineno)d]'))
    app.logger.addHandler(info_file_handler)

    # Testing Configuration
    app.logger.info("testing info.")
    app.logger.warn("testing warn.")
    app.logger.error("testing error.")

examples/app_template/base_app/home/__init__.py
__author__ = 'guy'

examples/app_template/base_app/home/views.py
from flask import Blueprint, redirect, url_for, render_template

home = Blueprint('home', __name__, template_folder='templates')


@home.route('/')
def homepage():
    return render_template('homepage.html')

examples/app_template/base_app/security_manager/__init__.py
__author__ = 'guy'

examples/app_template/base_app/security_manager/views.py
from flask import Blueprint, render_template, redirect, url_for
from flask.ext.security import current_user, login_required
from .forms import ChangeUserDetailsForm
from ..extensions import db
from .security_models import User

security_manager = Blueprint('security_manager', __name__,
                             template_folder='templates')


@login_required
@security_manager.route('/user_home')
def user_home():
    return render_template('user_home.html')


@login_required
@security_manager.route('/change_details', methods=['GET', 'POST'])
def change_details():
    user = db.session.query(User).filter(User.id == current_user.id).first()
    form = ChangeUserDetailsForm(obj=user)
    if form.validate_on_submit():
        form.populate_obj(user)
        db.session.commit()
        return redirect(url_for('.user_home'))
    return render_template('change_details.html', form=form)

examples/app_template/base_app/home/templates/homepage.html
{% extends 'sentidash/base.html' %}

{% block branding %}
    <a class="navbar-brand" href="#">Port Call {{ id }}</a>
{% endblock %}

{% block top_links %}
    {% include '_top_links.html' %}
{% endblock %}

{% block sidebar_items %}
{#    {% call dash_macros.render_multi_sitem('Main', active=main_active, icon_cls="fa-dashboard") %}#}
{#        {{ dash_macros.render_sitem('berth_manager.home', 'Home', id=id) }}#}
{#        {{ dash_macros.render_sitem('berth_manager.portcall_particulars', 'Port Call Details', id=id) }}#}
{#    {% endcall %}#}
    {{ dash_macros.render_sitem('home.homepage', 'Home', icon_cls="fa-dashboard") }}

{% endblock %}

examples/app_template/base_app/security_manager/templates/change_details.html
{% extends 'user_home.html' %}

{% block header %}
    {{ dash_macros.page_heading('Change User Details') }}
{% endblock %}

{% block body %}
    {{ form_macros.render_form(form, action_url=url_for('security_manager.change_details')) }}
{% endblock %}

examples/app_template/base_app/security_manager/templates/change_password.html
{% import 'sentidash/form_macros.html' as form_macros %}
{% import 'sentidash/macros.html' as dash_macros %}
{% extends 'sentidash/base.html' %}

{% block sidebar %}
{% endblock %}

{% block top_links %}
    {% include '_top_links.html' %}
{% endblock %}

{% block header %}
    {{ dash_macros.page_heading('Change Password') }}
{% endblock %}

{% block body %}
    {{ form_macros.render_form(change_password_form, cancel_url='', render_button=false) }}
{% endblock %}

examples/app_template/base_app/security_manager/templates/forgot_password.html
{% import 'sentidash/form_macros.html' as form_macros %}
{% import 'sentidash/macros.html' as dash_macros %}
{% extends 'sentidash/base.html' %}

{% block sidebar %}
{% endblock %}

{% block header %}
    {{ dash_macros.page_heading('Reset Password') }}
{% endblock %}

{% block body %}
    {{ form_macros.render_form(forgot_password_form, render_button=false, cancel_url='') }}
{% endblock %}

examples/app_template/base_app/security_manager/templates/login_user.html
{% from "sentisecurity/_macros.html" import render_errors %}
{% extends "sentidash/base.html" %}
    <!-- Custom styles for this template -->
{% block head_css %}
    {{ super() }}
    <style type="text/css">
        .form-signin {
            max-width: 330px;
            padding: 15px;
            margin: 0 auto;
        }
        .form-signin .form-signin-heading,
        .form-signin .checkbox {
            margin-bottom: 10px;
        }
        .form-signin .checkbox {
            font-weight: normal;
        }
        .form-signin .form-control {
            position: relative;
            height: auto;
            -webkit-box-sizing: border-box;
            -moz-box-sizing: border-box;
            box-sizing: border-box;
            padding: 10px;
            font-size: 16px;
        }
        .form-signin .form-control:focus {
            z-index: 2;
        }
        .form-signin input[type="email"] {
            margin-bottom: -1px;
            border-bottom-right-radius: 0;
            border-bottom-left-radius: 0;
        }
        .form-signin input[type="password"] {
            margin-bottom: 10px;
            border-top-left-radius: 0;
            border-top-right-radius: 0;
        }
        .form-signin ul li {
            color: #a94442
        }
    </style>
{% endblock %}

{% block top_links %}
    {% include '_top_links.html' %}
{% endblock %}

{% block body %}

    <div class="container">
        <form class="form-signin" action="{{ url_for('security.login') }}" method=post name="login_user_form">
            <h2 class="form-signin-heading">Please sign in</h2>
            {{ login_user_form.hidden_tag() }}
            {{ login_user_form.email(class="form-control", placeholder="Email address")|safe }}
            {{ render_errors(login_user_form.email) }}
            {{ login_user_form.password(class="form-control", placeholder="Password")|safe }}
            {{ render_errors(login_user_form.password) }}
            <p>Remember me{{ login_user_form.remember(class="checkbox")|safe }}</p>
            {{ render_errors(login_user_form.remember) }}
            <!--<input type="password" class="form-control" placeholder="Password" required name="{{ login_user_form.password }}">-->
            <button class="btn btn-lg btn-success btn-block" type="submit" value="Login">Sign in</button>
            <a class="btn btn-lg btn-info btn-block" href="{{ url_for('security.register') }}" style="padding-top:10px">Register</a>
        </form>
    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
{% endblock %}

examples/app_template/base_app/security_manager/templates/register_user.html
{% import 'sentidash/form_macros.html' as form_macros %}
{% import 'sentidash/macros.html' as dash_macros %}
{% extends 'sentidash/base.html' %}

{% block sidebar %}
{% endblock %}

{% block top_links %}
    {% include '_top_links.html' %}
{% endblock %}

{% block header %}
    {{ dash_macros.page_heading('Registration') }}
{% endblock %}

{% block body %}
    {{ form_macros.render_form(register_user_form, render_button=false, cancel_url='') }}
{% endblock %}

examples/app_template/base_app/security_manager/templates/reset_password.html
{% import 'sentidash/form_macros.html' as form_macros %}
{% import 'sentidash/macros.html' as dash_macros %}
{% extends 'sentidash/base.html' %}

{% block sidebar %}
{% endblock %}

{% block top_links %}
    {% include '_top_links.html' %}
{% endblock %}

{% block header %}
    {{ dash_macros.page_heading('Reset Password') }}
{% endblock %}

{% block body %}
    {{ form_macros.render_form(reset_password_form, render_button=false, cancel_url='') }}
{% endblock %}

examples/app_template/base_app/security_manager/templates/send_confirmation.html
{% import 'sentidash/form_macros.html' as form_macros %}
{% import 'sentidash/macros.html' as dash_macros %}
{% extends 'sentidash/base.html' %}

{% block sidebar %}
{% endblock %}

{% block top_links %}
    {% include '_top_links.html' %}
{% endblock %}

{% block header %}
    {{ dash_macros.page_heading('Send Confirmation') }}
{% endblock %}

{% block body %}
    {{ form_macros.render_form(send_confirmation_form, render_button=false, cancel_url='') }}
{% endblock %}

examples/app_template/base_app/security_manager/templates/user_home.html
{% extends 'sentidash/base.html' %}

{% block head_css %}
    {{ super() }}
    <style type="text/css">
        .btn-list {
            padding-top: 10px;
        }
    </style>

{% endblock %}

{% block top_links %}
    {% include '_top_links.html' %}
{% endblock %}

{% block header %}
    {{ dash_macros.page_heading('User Management: ' + current_user.name) }}
{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-9 col-push-3">
            <div class="panel panel-primary">
                <div class="panel-heading"><h3 class="panel-title">Details</h3></div>
                <div class="panel-body">
                    <table class="table table-bordered table-striped">
                        <tr>
                            <td>Email Address</td>
                            <td>{{ current_user.email }}</td>
                        </tr>
                        <tr>
                            <td>Name</td>
                            <td>{{ current_user.name }}</td>
                        </tr>
                        <tr>
                            <td>Confirmed At</td>
                            <td>{{ current_user.confirmed_at }}</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-md-9 btn-list">
            <a class="btn btn-default btn-block" href="{{ url_for('security_manager.change_details') }}">Change User Details</a>
        </div>
        <div class="col-md-9 btn-list">
            <a class="btn btn-default btn-block" href="{{ url_for('security.change_password') }}">Change Password</a>
        </div>
        <div class="col-md-9 btn-list">
            <a class="btn btn-default btn-block" href="{{ url_for('security.send_confirmation') }}">Resend Confirmation Email</a>
        </div>

    </div>
{% endblock %}

examples/app_template/base_app/templates/_top_links.html
{% import 'sentidash/macros.html' as dash_macros %}

<li><a href="{{ url_for('admin.index') }}"><i class="fa fa-database"></i> Admin</a></li>
{% if current_user.is_authenticated() %}
    <li><a href="{{ url_for('security_manager.user_home') }}"><i class="fa fa-user"> User</i></a></li>
    <li><a href="{{ url_for('security.logout') }}">Log Out</a></li>
{% else %}
    <li><a href="{{ url_for('security.login') }}">Log In</a></li>
{% endif %}